server:
  port: 9004
spring:
  application:
    name: scaffolding-article
  data:
    mongodb:
      uri: mongodb://root:root@192.168.153.128:27017/
      database: recruitdb
      authentication-database: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/scaffolding_article?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    name: article
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 30000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: select '1' from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
#    filters: stat,wall,log4j
  redis:
    host: 192.168.153.128
    port: 6379
    timeout: 10000
    database: 0
    password:
    jedis:
      pool:
        min-idle: 20
        max-idle: 100
        max-active: 300
        max-wait: -1
    lettuce:
      pool:
        max-active: 300
        max-idle: 100
        max-wait: -1
        min-idle: 20
      shutdown-timeout: 10000
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.amor.article.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eurekaUserName}:${eurekaPassWord}@peer1:8761/eureka/,http://${eurekaUserName}:${eurekaPassWord}@peer2:8762/eureka/,http://${eurekaUserName}:${eurekaPassWord}@peer3:8763/eureka/
  instance:
    prefer‐ip‐address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
eurekaUserName: amor
eurekaPassWord: amor
swagger:
  name: LHL
  url: LHLLAB
  email: xxx@gmail.com
  title:  scaffolding-article
  terms-of-service-url: https://github.com/412Aomr
  license:  apach 2.0
  licenseUrl:  www.amor.com
  version:  1.0
jwt:
 config:
  key: amor
  ttl: 36000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
    
