server:
  port: 9007
spring:
  application:
    name: scaffolding-search
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    #default-property-inclusion: non_null
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
elasticsearch:
  ip: 192.168.153.128:9200
swagger:
  name: LHL
  url: LHLLAB
  email: xxx@gmail.com
  title:  scaffolding-search
  terms-of-service-url: https://github.com/SophiaLeo
  license:  apach 2.0
  licenseUrl:  www.amor.com
  version:  1.0
management:
  endpoints:
    web:
      exposure:
        include: "*"  #因为springboot2.1.必须加上,支持访问/actuator/hystrix.stream
  endpoint:
    bus-refresh:
      enabled: true
  security:
    enabled: false
