server: 
  port: 9012 
spring: 
  application: 
    name: scaffolding-web
zuul:
  routes:
    scaffolding-gathering:
      path: /gathering/**
      serviceId: scaffolding-gathering
    scaffolding-article:
      path: /article/**
      serviceId: scaffolding-article
    scaffolding-base:
      path: /base/**
      serviceId: scaffolding-base
    scaffolding-friend:
      path: /friend/**
      serviceId: scaffolding-friend
    scaffolding-qa:
      path: /qa/**
      serviceId: scaffolding-qa
    scaffolding-recruit:
      path: /recruit/**
      serviceId: scaffolding-recruit
    scaffolding-spit:
      path: /spit/**
      serviceId: scaffolding-spit
    scaffolding-user:
      path: /user/**
      serviceId: scaffolding-user
    scaffolding-search:
      path: /search/**
      serviceId: scaffolding-search
    scaffolding-sms:
      path: /sms/**
      serviceId: scaffolding-sms
    scaffolding-auth:
      path: /auth/**
      serviceId: scaffolding-auth
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:${server.port}/auth/api/user
      prefer-token-info: false
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3500
jwt:
  config:
    key: amor
    ttl: 36000
management:
  endpoints:
    web:
      exposure:
        include: "*"  #因为springboot2.1.必须加上,支持访问/actuator/hystrix.stream
  endpoint:
    bus-refresh:
      enabled: true
  security:
    enabled: false
